/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoadImage;

/**
 *
 * @author DELL
 */
public class mainWindows extends javax.swing.JFrame {

    /**
     * Creates new form mainWindows
     */
    public mainWindows() {
        initComponents();
        LoadImage Fondo=new LoadImage ("/img/Fondo.jpg",lbl_fondo.getHeight(),lbl_fondo.getWidth());
        lbl_fondo.setIcon(Fondo.getImg());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_pro1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_pro2 = new javax.swing.JButton();
        lbl_nombre1 = new javax.swing.JLabel();
        btn_iniciar_sesion = new javax.swing.JButton();
        btn_pro4 = new javax.swing.JButton();
        lbl_nombre2 = new javax.swing.JLabel();
        btn_pro5 = new javax.swing.JButton();
        lbl_nombre3 = new javax.swing.JLabel();
        lbl_nombre4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_detalle1 = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_detalle3 = new javax.swing.JTextPane();
        lbl_precio1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_detalle4 = new javax.swing.JTextPane();
        lbl_precio2 = new javax.swing.JLabel();
        lbl_precio3 = new javax.swing.JLabel();
        lbl_precio4 = new javax.swing.JLabel();
        txt_detalle2 = new javax.swing.JScrollPane();
        txt_datalle2 = new javax.swing.JTextPane();
        btn_anterior = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_img1 = new javax.swing.JLabel();
        lbl_img3 = new javax.swing.JLabel();
        lbl_img2 = new javax.swing.JLabel();
        lbl_img4 = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pro1.setText("AÑADIR AL CARRITO");
        btn_pro1.setName(""); // NOI18N
        jPanel1.add(btn_pro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        jLabel1.setText("CATALOGO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 230, -1));

        btn_pro2.setText("AÑADIR AL CARRITO");
        btn_pro2.setName(""); // NOI18N
        jPanel1.add(btn_pro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        lbl_nombre1.setText("Fresh ME 20 Lt");
        jPanel1.add(lbl_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btn_iniciar_sesion.setText("INICIAR SESION");
        jPanel1.add(btn_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        btn_pro4.setText("AÑADIR AL CARRITO");
        btn_pro4.setName(""); // NOI18N
        jPanel1.add(btn_pro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        lbl_nombre2.setText("Fresh ME Limon 1.5 Lt");
        jPanel1.add(lbl_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btn_pro5.setText("AÑADIR AL CARRITO");
        btn_pro5.setName(""); // NOI18N
        jPanel1.add(btn_pro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        lbl_nombre3.setText("Fresh ME 7 Lt");
        jPanel1.add(lbl_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        lbl_nombre4.setText("Fresh ME 3 Lt");
        jPanel1.add(lbl_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel8.setText("PRECIO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        jLabel9.setText("PRECIO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 60, 30));

        txt_detalle1.setText("Agua Mineral refrescante 20 Litros");
        jScrollPane2.setViewportView(txt_detalle1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 60));

        jLabel11.setText("PRECIO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel12.setText("PRECIO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        txt_detalle3.setText("Agua Mineral refrescante 7 Litros");
        jScrollPane3.setViewportView(txt_detalle3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 110, 60));

        lbl_precio1.setText("70 BS");
        jPanel1.add(lbl_precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        txt_detalle4.setText("Agua Mineral refrescante 3 Litros");
        jScrollPane4.setViewportView(txt_detalle4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 110, 60));

        lbl_precio2.setText("15 BS");
        jPanel1.add(lbl_precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        lbl_precio3.setText("30 BS");
        jPanel1.add(lbl_precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        lbl_precio4.setText("20 BS");
        jPanel1.add(lbl_precio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        txt_datalle2.setText("Bedida Refrescante base de agua y zumo sensacion limon 1.5 Litros");
        txt_detalle2.setViewportView(txt_datalle2);

        jPanel1.add(txt_detalle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 70));

        btn_anterior.setText("<");
        jPanel1.add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, -1));

        btn_siguiente.setText(">");
        jPanel1.add(btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));
        jPanel1.add(lbl_img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, 90));
        jPanel1.add(lbl_img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 100, 90));
        jPanel1.add(lbl_img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, 90));
        jPanel1.add(lbl_img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 100, 90));
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_anterior;
    public javax.swing.JButton btn_iniciar_sesion;
    public javax.swing.JButton btn_pro1;
    public javax.swing.JButton btn_pro2;
    public javax.swing.JButton btn_pro4;
    public javax.swing.JButton btn_pro5;
    public javax.swing.JButton btn_siguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_fondo;
    public javax.swing.JLabel lbl_img1;
    public javax.swing.JLabel lbl_img2;
    public javax.swing.JLabel lbl_img3;
    public javax.swing.JLabel lbl_img4;
    public javax.swing.JLabel lbl_nombre1;
    public javax.swing.JLabel lbl_nombre2;
    public javax.swing.JLabel lbl_nombre3;
    public javax.swing.JLabel lbl_nombre4;
    public javax.swing.JLabel lbl_precio1;
    public javax.swing.JLabel lbl_precio2;
    public javax.swing.JLabel lbl_precio3;
    public javax.swing.JLabel lbl_precio4;
    public javax.swing.JTextPane txt_datalle2;
    public javax.swing.JTextPane txt_detalle1;
    private javax.swing.JScrollPane txt_detalle2;
    public javax.swing.JTextPane txt_detalle3;
    public javax.swing.JTextPane txt_detalle4;
    // End of variables declaration//GEN-END:variables
}
